const $=id=>document.getElementById(id);
const names=['Nord','Est','Sud','Ouest'];
const allBays=[0.8,1,1.2,1.5,2,2.5,3];
const families=['Structure','Planchers','Protection','Accès','Contreventement','Consoles','Amarrages'];
const fmt=n=>Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:2});
const clone=o=>JSON.parse(JSON.stringify(o));
let state={
  name:'Maison',mode:'auto',startHeight:1,targetHeight:7,levelHeight:2,angle:-.65,active:0,listFacade:'all',
  stock:{system:'r200p',width:.8,bays:[1.5,2,2.5,3],families:Object.fromEntries(families.map(x=>[x,true])),deck:'alu-bois',guardrail:'fusio',diagonal:'rcm'},
  familyFilters:Object.fromEntries(families.map(x=>[x,true])),facades:[]
};
function levels(){return Math.max(1,Math.ceil((state.targetHeight-state.startHeight)/state.levelHeight))}
function baySum(fa){return fa.bays.reduce((s,b)=>s+b.length,0)}
function totalLen(fa){return baySum(fa)+(+fa.overlapLeft||0)+(+fa.overlapRight||0)}
function splitLength(total){const avail=[...state.stock.bays].sort((a,b)=>a-b),out=[];let r=+total;while(r>.01){let x=avail.filter(p=>p<=r+.01).pop()||avail[0];if(!x)break;out.push({length:x});r=+(r-x).toFixed(2);if(r>0&&r<avail[0]*.7){out[out.length-1].length=+(out[out.length-1].length+r).toFixed(2);r=0}}return out}
function defaultFacade(len,i){return{name:names[i],target:len,bays:splitLength(len),overlapLeft:.8,overlapRight:.8,accessBay:-1,console:'none',includeAnchors:true}}
function switchTab(id){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='materials')renderMaterials();if(id==='view3d')draw3D()}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
function renderStock(){
  $('stockSystem').value=state.stock.system;$('scaffoldWidth').value=state.stock.width;$('stockDeck').value=state.stock.deck;$('stockGuardrail').value=state.stock.guardrail;$('stockDiagonal').value=state.stock.diagonal;
  $('bayChoices').innerHTML=allBays.map(x=>`<label class="choice"><input type="checkbox" data-bay="${x}" ${state.stock.bays.includes(x)?'checked':''}><span>${fmt(x)} m</span></label>`).join('');
  $('stockFamilies').innerHTML=families.map(x=>`<label class="choice"><input type="checkbox" data-stockfam="${x}" ${state.stock.families[x]?'checked':''}><span>${x}</span></label>`).join('');
  $('stockSummary').innerHTML=`<strong>Configuration actuelle :</strong> ${labelSystem(state.stock.system)} · largeur ${fmt(state.stock.width)} m · travées ${state.stock.bays.map(x=>fmt(x)).join(' / ')} m`;
}
function readStock(){
  state.stock.system=$('stockSystem').value;state.stock.width=+$('scaffoldWidth').value;state.stock.deck=$('stockDeck').value;state.stock.guardrail=$('stockGuardrail').value;state.stock.diagonal=$('stockDiagonal').value;
  state.stock.bays=[...document.querySelectorAll('[data-bay]:checked')].map(x=>+x.dataset.bay).sort((a,b)=>a-b);if(!state.stock.bays.length){alert('Choisis au moins une longueur de travée.');return false}
  families.forEach(f=>state.stock.families[f]=!!document.querySelector(`[data-stockfam="${f}"]`)?.checked);renderStock();return true;
}
$('validateStock').onclick=()=>{if(readStock())switchTab('project')};
['stockSystem','scaffoldWidth','stockDeck','stockGuardrail','stockDiagonal'].forEach(id=>$(id).addEventListener('change',readStock));
function labelSystem(s){return s==='r200p'?'R200 Progress acier':s==='r200r'?'R200 Record aluminium':'M368 multidirectionnel'}
function sync(){state.name=$('name').value||'Maison';state.mode=$('mode').value;state.startHeight=+$('startHeight').value||0;state.targetHeight=+$('targetHeight').value||1;state.levelHeight=+$('levelHeight').value||2;updateStats()}
['name','mode','startHeight','targetHeight','levelHeight','width','depth'].forEach(id=>$(id).addEventListener('input',sync));
function makeFacades(){sync();const w=+$('width').value||12,d=+$('depth').value||8;state.facades=[w,d,w,d].map(defaultFacade);state.active=0;renderAll();switchTab('facades')}
$('generate').onclick=makeFacades;
function updateStats(){const per=state.facades.length?state.facades.reduce((s,x)=>s+totalLen(x),0):2*((+$('width').value||0)+(+ $('depth').value||0));$('perimeter').textContent=fmt(per)+' m';$('levelsStat').textContent=levels();$('area').textContent=fmt(per*Math.max(0,state.targetHeight-state.startHeight))+' m²'}
function renderEditor(){
 const sel=$('activeFacade');sel.innerHTML=state.facades.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('');sel.value=state.active;sel.onchange=()=>{state.active=+sel.value;renderEditor();draw2D();draw3D()};
 const box=$('facadeEditor');if(!state.facades.length){box.innerHTML='<p>Crée d’abord les quatre façades.</p>';return}const fa=state.facades[state.active];
 box.innerHTML=`<div class="facade-card"><div class="top"><strong>Façade ${fa.name} — ${fmt(baySum(fa))} m + chevauchements = ${fmt(totalLen(fa))} m</strong><button id="addBay">+ Travée</button></div>
 <div class="grid3"><label>Longueur cible<input id="facadeTarget" type="number" step="0.1" value="${fa.target}"></label><label>Chevauchement gauche<input id="overlapLeft" type="number" min="0" step="0.1" value="${fa.overlapLeft}"></label><label>Chevauchement droit<input id="overlapRight" type="number" min="0" step="0.1" value="${fa.overlapRight}"></label></div>
 <div class="grid3"><label>Travée d'accès<select id="accessBay"><option value="-1">Aucune</option>${fa.bays.map((b,i)=>`<option value="${i}" ${fa.accessBay===i?'selected':''}>Travée ${i+1}</option>`).join('')}</select></label><label>Consoles<select id="console"><option value="none">Aucune</option><option value="inside" ${fa.console==='inside'?'selected':''}>Côté façade</option><option value="outside" ${fa.console==='outside'?'selected':''}>Côté extérieur</option></select></label><label class="inline"><input id="includeAnchors" type="checkbox" ${fa.includeAnchors?'checked':''}> Inclure les amarrages</label></div>
 <button id="recalcFacade">Recalculer cette façade</button>
 <div class="bay-grid">${fa.bays.map((b,i)=>`<div class="bay ${fa.accessBay===i?'access':''}"><strong>Travée ${i+1}${fa.accessBay===i?' — ACCÈS':''}</strong><label>Longueur<select data-len="${i}">${state.stock.bays.map(p=>`<option value="${p}" ${Math.abs(p-b.length)<.01?'selected':''}>${fmt(p)} m</option>`).join('')}</select></label><button class="remove" data-r="${i}">Supprimer</button></div>`).join('')}</div></div>`;
 $('addBay').onclick=()=>{fa.bays.push({length:state.stock.bays[state.stock.bays.length-1]});renderAll()};
 $('recalcFacade').onclick=()=>{fa.target=+$('facadeTarget').value||fa.target;fa.bays=splitLength(fa.target);fa.accessBay=-1;renderAll()};
 ['overlapLeft','overlapRight'].forEach(id=>$(id).oninput=()=>{fa[id]=+$(id).value||0;renderAll(false)});
 $('accessBay').onchange=()=>{fa.accessBay=+$('accessBay').value;renderAll()};$('console').onchange=()=>{fa.console=$('console').value;renderAll()};$('includeAnchors').onchange=()=>{fa.includeAnchors=$('includeAnchors').checked;renderMaterials()};
 box.querySelectorAll('[data-len]').forEach(e=>e.onchange=()=>{fa.bays[+e.dataset.len].length=+e.value;renderAll()});box.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{fa.bays.splice(+e.dataset.r,1);fa.accessBay=-1;renderAll()});
}
function renderChecks(){const out=[];if(state.stock.system==='r200r'&&state.stock.diagonal==='dv')out.push(['bad','R200 Record : utiliser des diagonales RCM, pas DV.']);if(!state.stock.families.Structure)out.push(['warn','La famille Structure est désactivée.']);if(state.facades.some(f=>Math.abs(baySum(f)-f.target)>.15))out.push(['warn','Une façade ne correspond pas exactement à sa longueur cible.']);if(!out.length)out.push(['ok','Configuration cohérente pour une préparation de matériel.']);$('checks').innerHTML=out.map(x=>`<div class="check ${x[0]}">${x[1]}</div>`).join('')}
function draw2D(){const c=$('plan'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.save();x.translate(600,380);x.strokeStyle='#334155';x.lineWidth=8;const w=380,d=240;x.strokeRect(-w/2,-d/2,w,d);x.lineWidth=3;state.facades.forEach((fa,i)=>{x.strokeStyle=['#f59e0b','#0f766e','#7c3aed','#dc2626'][i];x.beginPath();if(i===0){x.moveTo(-w/2-fa.overlapLeft*12,-d/2-35);x.lineTo(w/2+fa.overlapRight*12,-d/2-35)}if(i===1){x.moveTo(w/2+35,-d/2-fa.overlapLeft*12);x.lineTo(w/2+35,d/2+fa.overlapRight*12)}if(i===2){x.moveTo(w/2+fa.overlapLeft*12,d/2+35);x.lineTo(-w/2-fa.overlapRight*12,d/2+35)}if(i===3){x.moveTo(-w/2-35,d/2+fa.overlapLeft*12);x.lineTo(-w/2-35,-d/2-fa.overlapRight*12)}x.stroke()});x.restore()}
function iso(x,y,z){const a=state.angle,ca=Math.cos(a),sa=Math.sin(a);const rx=x*ca-y*sa,ry=x*sa+y*ca;return[600+rx*30,690-ry*15-z*30]}
function line(ctx,a,b,style='#334155',width=2){ctx.strokeStyle=style;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
function drawFacade3D(ctx,fa,i){const buildingW=12,buildingD=8,offset=state.stock.width+0.45;let start,end,normal;
 if(i===0){start=[-buildingW/2-fa.overlapLeft,-buildingD/2-offset];end=[buildingW/2+fa.overlapRight,-buildingD/2-offset];normal=[0,-1]}
 if(i===1){start=[buildingW/2+offset,-buildingD/2-fa.overlapLeft];end=[buildingW/2+offset,buildingD/2+fa.overlapRight];normal=[1,0]}
 if(i===2){start=[buildingW/2+fa.overlapLeft,buildingD/2+offset];end=[-buildingW/2-fa.overlapRight,buildingD/2+offset];normal=[0,1]}
 if(i===3){start=[-buildingW/2-offset,buildingD/2+fa.overlapLeft];end=[-buildingW/2-offset,-buildingD/2-fa.overlapRight];normal=[-1,0]}
 const total=fa.bays.reduce((s,b)=>s+b.length,0),extra=fa.overlapLeft+fa.overlapRight,scale=(Math.hypot(end[0]-start[0],end[1]-start[1]))/(total+extra||1);let marks=[0,fa.overlapLeft];let cur=fa.overlapLeft;fa.bays.forEach(b=>{cur+=b.length;marks.push(cur)});marks.push(cur+fa.overlapRight);
 const dx=end[0]-start[0],dy=end[1]-start[1],L=total+extra||1;const points=marks.map(m=>[start[0]+dx*m/L,start[1]+dy*m/L]);const h=levels()*state.levelHeight;
 for(let row=0;row<2;row++){const ox=normal[0]*state.stock.width*row,oy=normal[1]*state.stock.width*row;points.forEach(p=>line(ctx,iso(p[0]+ox,p[1]+oy,state.startHeight),iso(p[0]+ox,p[1]+oy,state.startHeight+h),'#334155',2));for(let lv=0;lv<=levels();lv++){const z=state.startHeight+lv*state.levelHeight;for(let j=0;j<points.length-1;j++)line(ctx,iso(points[j][0]+ox,points[j][1]+oy,z),iso(points[j+1][0]+ox,points[j+1][1]+oy,z),i===state.active?'#f59e0b':'#64748b',2)}}
 points.forEach(p=>{for(let lv=0;lv<=levels();lv++){const z=state.startHeight+lv*state.levelHeight;line(ctx,iso(p[0],p[1],z),iso(p[0]+normal[0]*state.stock.width,p[1]+normal[1]*state.stock.width,z),'#0f172a',2)}});
 for(let j=1;j<points.length-2;j++){const p=points[j],q=points[j+1];for(let lv=0;lv<levels();lv++){const z=state.startHeight+lv*state.levelHeight+.05;const a=iso(p[0],p[1],z),b=iso(q[0]+normal[0]*state.stock.width,q[1]+normal[1]*state.stock.width,z);line(ctx,a,b,'#94a3b8',5)}}
}
function draw3D(){const c=$('three'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,c.width,c.height);const bw=12,bd=8,h=Math.max(4,state.targetHeight);const corners=[[-bw/2,-bd/2],[bw/2,-bd/2],[bw/2,bd/2],[-bw/2,bd/2]];ctx.fillStyle='#e2e8f0';ctx.beginPath();ctx.moveTo(...iso(...corners[0],0));corners.slice(1).forEach(p=>ctx.lineTo(...iso(...p,0)));ctx.closePath();ctx.fill();corners.forEach((p,i)=>{line(ctx,iso(...p,0),iso(...p,h),'#94a3b8',2);line(ctx,iso(...p,h),iso(...corners[(i+1)%4],h),'#94a3b8',2)});state.facades.forEach((fa,i)=>drawFacade3D(ctx,fa,i));ctx.fillStyle='#172033';ctx.font='bold 24px sans-serif';ctx.fillText(`Largeur échafaudage : ${fmt(state.stock.width)} m`,30,45);ctx.font='18px sans-serif';ctx.fillText('Chaque séparation verticale représente une travée.',30,75)}
const refs={base:{r200p:['04101003','Socle à vis articulé',3.5],r200r:['04101003','Socle à vis articulé',3.5],m368:['04101003','Socle à vis articulé',3.5]},frame:{r200p:['04002004','R3 Cadre en H 2,00 m acier',15.9],r200r:['04702010','R3 Cadre en H 2,00 m aluminium',8.6],m368:['00026710','M4200 montant 2,00 m',10.4]}};
function add(map,fam,fac,code,name,qty,weight=0,note=''){const k=[fam,code,name].join('|');if(!map[k])map[k]={fam,facades:new Set(),code,name,qty:0,weight,note};map[k].qty+=qty;map[k].facades.add(fac)}
function materialRows(){const map={};state.facades.forEach((fa,fi)=>{if(state.listFacade!=='all'&&+state.listFacade!==fi)return;const fac=fa.name,lev=levels(),posts=fa.bays.length+1;if(state.stock.families.Structure){add(map,'Structure',fac,...refs.base[state.stock.system],posts*2);add(map,'Structure',fac,...refs.frame[state.stock.system],posts*lev)}fa.bays.forEach((b,bi)=>{if(state.stock.families.Planchers)add(map,bi===fa.accessBay?'Accès':'Planchers',fac,'Selon longueur',`${state.stock.deck==='alu-bois'?'Plancher alu-bois':state.stock.deck==='acier'?'Plancher acier':'Plancher aluminium'} ${fmt(b.length)} m`,lev,0,bi===fa.accessBay?'Version à trappe':'');if(state.stock.families.Protection)add(map,'Protection',fac,'Selon longueur',`${state.stock.guardrail==='fusio'?'Garde-corps Fusio':'Lisses de protection'} ${fmt(b.length)} m`,lev)});if(state.stock.families.Contreventement)add(map,'Contreventement',fac,state.stock.diagonal==='dv'?'04105006':'04005007',`Diagonale ${state.stock.diagonal.toUpperCase()}`,Math.ceil(fa.bays.length/3)*lev,state.stock.diagonal==='dv'?8.8:6.4);if(fa.accessBay>=0&&state.stock.families.Accès)add(map,'Accès',fac,'Selon montage','Échelles d’accès',lev,0);if(fa.console!=='none'&&state.stock.families.Consoles)add(map,'Consoles',fac,'Selon largeur',`Consoles côté ${fa.console==='inside'?'façade':'extérieur'}`,fa.bays.length*lev,0);if(fa.includeAnchors&&state.stock.families.Amarrages)add(map,'Amarrages',fac,'Selon support','Amarrages / ancrages',Math.max(2,Math.ceil(fa.bays.length/2)*Math.ceil(lev/2)),0,'Implantation à vérifier')});return Object.values(map).map(r=>({...r,fac:[...r.facades].join(', ')}))}
function renderMaterials(){const sf=$('listFacade');sf.innerHTML='<option value="all">Total chantier</option>'+state.facades.map((fa,i)=>`<option value="${i}">${fa.name}</option>`).join('');sf.value=state.listFacade;sf.onchange=()=>{state.listFacade=sf.value;renderMaterials()};$('familyFilters').innerHTML=families.filter(f=>state.stock.families[f]).map(f=>`<label class="chip"><input type="checkbox" data-fam="${f}" ${state.familyFilters[f]!==false?'checked':''}>${f}</label>`).join('');$('familyFilters').querySelectorAll('[data-fam]').forEach(e=>e.onchange=()=>{state.familyFilters[e.dataset.fam]=e.checked;renderMaterials()});$('matTitle').textContent=`${state.name} — ${state.listFacade==='all'?'total chantier':'façade '+state.facades[+state.listFacade]?.name}`;const rows=materialRows().filter(r=>state.familyFilters[r.fam]!==false);let total=0,g='';$('matList').innerHTML=rows.map(r=>{total+=r.qty*r.weight;const head=r.fam!==g?(g=r.fam,`<h3 class="group">${r.fam}</h3>`):'';return head+`<div class="mat-row"><span class="code">${r.code}</span><span><strong>${r.name}</strong>${r.note?`<small>${r.note}</small>`:''}</span><span>${r.fac}</span><span class="qty">${r.qty}</span><span>${r.weight?fmt(r.qty*r.weight)+' kg':'—'}</span></div>`}).join('')+`<div class="total"><strong>Poids indicatif connu</strong><strong>${fmt(total)} kg</strong></div>`}
function renderSaved(){const a=JSON.parse(localStorage.getItem('scaffr200-v31-projects')||'[]'),b=$('savedList');b.innerHTML=a.length?'':'<p>Aucun chantier.</p>';a.forEach((p,i)=>b.insertAdjacentHTML('beforeend',`<div class="saved"><div><strong>${p.name}</strong><small>${p.facades.length} façades</small></div><button data-open="${i}">Ouvrir</button></div>`));b.querySelectorAll('[data-open]').forEach(e=>e.onclick=()=>{state=a[+e.dataset.open];loadForm();renderAll();switchTab('project')})}
$('save').onclick=()=>{const a=JSON.parse(localStorage.getItem('scaffr200-v31-projects')||'[]'),p=clone(state);p.savedAt=Date.now();a.unshift(p);localStorage.setItem('scaffr200-v31-projects',JSON.stringify(a.slice(0,30)));renderSaved()};$('print').onclick=()=>window.print();$('left').onclick=()=>{state.angle-=.18;draw3D()};$('right').onclick=()=>{state.angle+=.18;draw3D()};$('reset').onclick=()=>{state.angle=-.65;draw3D()};let drag=false,last=0;$('three').onpointerdown=e=>{drag=true;last=e.clientX};$('three').onpointermove=e=>{if(drag){state.angle+=(e.clientX-last)/250;last=e.clientX;draw3D()}};window.onpointerup=()=>drag=false;
$('exportJson').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.name.replace(/[^a-z0-9]+/gi,'_')}_ScaffR200_V31.json`;a.click()};$('importJson').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);loadForm();renderAll()}catch{alert('Fichier invalide')}};r.readAsText(e.target.files[0])};
function loadForm(){$('name').value=state.name;$('mode').value=state.mode;$('startHeight').value=state.startHeight;$('targetHeight').value=state.targetHeight;$('levelHeight').value=state.levelHeight;if(state.facades.length){$('width').value=state.facades[0].target;$('depth').value=state.facades[1].target}renderStock()}
function renderAll(editor=true){updateStats();if(editor)renderEditor();renderChecks();draw2D();draw3D();renderMaterials();renderSaved();renderStock()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');renderStock();makeFacades();switchTab('stock');
