const tbody=document.querySelector('#catalogue');const search=document.querySelector('#search');const statusEl=document.querySelector('#status');
let items=[],onlySelected=false;let quantities=JSON.parse(localStorage.getItem('scaffr200-quantities')||'{}');
const fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n);
function save(){localStorage.setItem('scaffr200-quantities',JSON.stringify(quantities));statusEl.textContent='Enregistré';setTimeout(()=>statusEl.textContent='',1500)}
function render(){const q=search.value.trim().toLowerCase();tbody.innerHTML='';items.filter(x=>{const qty=Number(quantities[x.reference]||0);const match=(x.reference+' '+x.designation+' '+x.dimensions).toLowerCase().includes(q);return match&&(!onlySelected||qty>0)}).forEach(x=>{const qty=Number(quantities[x.reference]||0);const tr=document.createElement('tr');if(qty>0)tr.className='selected';tr.innerHTML=`<td>${x.reference}</td><td>${x.designation}</td><td>${x.dimensions||'—'}</td><td>${x.poids?x.poids+' kg':'—'}</td><td><input class="qty" type="number" min="0" step="1" value="${qty}" data-ref="${x.reference}"></td>`;tbody.appendChild(tr)});updateSummary()}
function updateSummary(){let lines=0,total=0,weight=0;for(const x of items){const n=Number(quantities[x.reference]||0);if(n>0){lines++;total+=n;weight+=n*Number((x.poids||'0').replace(',','.'))}}document.querySelector('#lineCount').textContent=`${lines} article${lines>1?'s':''} sélectionné${lines>1?'s':''}`;document.querySelector('#totalQty').textContent=`Quantité totale : ${total}`;document.querySelector('#totalWeight').textContent=`Poids estimé : ${fmt(weight)} kg`}
tbody.addEventListener('input',e=>{if(!e.target.matches('.qty'))return;quantities[e.target.dataset.ref]=Math.max(0,Number(e.target.value||0));e.target.closest('tr').classList.toggle('selected',quantities[e.target.dataset.ref]>0);updateSummary();save()});
search.addEventListener('input',render);document.querySelector('#showSelected').onclick=e=>{onlySelected=!onlySelected;e.target.textContent=onlySelected?'Voir toute la liste':'Voir seulement les quantités';render()};
document.querySelector('#resetBtn').onclick=()=>{if(confirm('Remettre toutes les quantités à zéro ?')){quantities={};save();render()}};document.querySelector('#saveBtn').onclick=save;document.querySelector('#printBtn').onclick=()=>window.print();
document.querySelector('#exportCsv').onclick=()=>{const rows=[['Référence','Désignation','Dimensions','Poids unitaire kg','Quantité','Poids total kg']];items.forEach(x=>{const n=Number(quantities[x.reference]||0);if(n>0)rows.push([x.reference,x.designation,x.dimensions,x.poids,n,(n*Number((x.poids||'0').replace(',','.'))).toFixed(1).replace('.',',')])});const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('
');const blob=new Blob(['﻿'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='liste-materiel-scaffr200.csv';a.click();URL.revokeObjectURL(a.href)};
fetch('catalogue.json').then(r=>r.json()).then(data=>{items=data;render()}).catch(()=>{tbody.innerHTML='<tr><td colspan="5">Impossible de charger catalogue.json. Ouvrez l’application avec un petit serveur local ou déposez tous les fichiers sur GitHub Pages.</td></tr>'});