const $=id=>document.getElementById(id), names=['Nord','Est','Sud','Ouest'], presets=[0.7,1,1.5,2,2.5,3];
let state={name:'Maison',mode:'auto',startHeight:1,targetHeight:7,levelHeight:2,angle:-.65,active:0,facades:[]};
const f=n=>Number(n).toLocaleString('fr-FR',{maximumFractionDigits:2});
function levels(){return Math.max(1,Math.ceil((state.targetHeight-state.startHeight)/state.levelHeight))}
function scaffoldTop(){return state.startHeight+levels()*state.levelHeight}
function splitLength(total){const out=[];let r=+total;while(r>0.01){let x=presets.filter(p=>p<=r+.01).pop()||Math.min(r,.7);if(r-x>0&&r-x<.7){x=Math.max(.7,+(x-(.7-(r-x))).toFixed(2))}out.push({length:+Math.min(x,r).toFixed(2),type:'standard',frame:'full'});r=+(r-x).toFixed(2)}return out}
function makeFacades(){const w=+$('width').value||12,d=+$('depth').value||8;state.facades=[w,d,w,d].map((len,i)=>({name:names[i],target:len,bays:splitLength(len)}));state.active=0;renderAll();switchTab('facades')}
function sync(){state.name=$('name').value||'Maison';state.mode=$('mode').value;state.startHeight=+$('startHeight').value;state.targetHeight=+$('targetHeight').value||1;state.levelHeight=+$('levelHeight').value||2;renderAll(false)}
function switchTab(id){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='materials')renderMaterials()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));['name','mode','startHeight','targetHeight','levelHeight','width','depth'].forEach(id=>$(id).oninput=sync);$('generate').onclick=makeFacades;
function updateStats(){const per=state.facades.length?state.facades.reduce((s,x)=>s+x.bays.reduce((a,b)=>a+b.length,0),0):2*((+$('width').value||0)+(+ $('depth').value||0));$('perimeter').textContent=f(per)+' m';$('levelsStat').textContent=levels();$('area').textContent=f(per*state.targetHeight)+' m²'}
function renderEditor(){const sel=$('activeFacade');sel.innerHTML=state.facades.map((x,i)=>`<option value="${i}" ${i===state.active?'selected':''}>${x.name}</option>`).join('');sel.onchange=()=>{state.active=+sel.value;renderEditor();draw2D()};const box=$('facadeEditor');if(!state.facades.length){box.innerHTML='<p>Crée d’abord les quatre façades.</p>';return}const fa=state.facades[state.active];box.innerHTML=`<div class="facade-card"><div class="top"><strong>Façade ${fa.name} — ${f(fa.bays.reduce((s,b)=>s+b.length,0))} m</strong><button id="addBay">+ Travée</button></div><div class="bay-grid">${fa.bays.map((b,i)=>`<div class="bay"><strong>Travée ${i+1}</strong><label>Longueur<select data-l="${i}">${presets.map(p=>`<option value="${p}" ${p===b.length?'selected':''}>${f(p)} m</option>`).join('')}<option value="custom" ${presets.includes(b.length)?'':'selected'}>Personnalisée</option></select></label><label>Type<select data-t="${i}"><option value="standard" ${b.type==='standard'?'selected':''}>Standard</option><option value="access" ${b.type==='access'?'selected':''}>Accès</option><option value="angle" ${b.type==='angle'?'selected':''}>Angle</option></select></label><label>Cadre<select data-f="${i}"><option value="full" ${b.frame==='full'?'selected':''}>Cadre complet</option><option value="half-bottom" ${b.frame==='half-bottom'?'selected':''}>Demi-cadre en bas</option><option value="half-top" ${b.frame==='half-top'?'selected':''}>Demi-cadre en haut</option></select></label><button class="remove" data-r="${i}">Supprimer</button></div>`).join('')}</div></div>`;$('addBay').onclick=()=>{fa.bays.push({length:3,type:'standard',frame:'full'});renderAll()};box.querySelectorAll('[data-l]').forEach(e=>e.onchange=()=>{const i=+e.dataset.l;if(e.value==='custom'){const v=prompt('Longueur en mètres',fa.bays[i].length);if(v)fa.bays[i].length=Math.max(.3,+v)}else fa.bays[i].length=+e.value;renderAll()});box.querySelectorAll('[data-t]').forEach(e=>e.onchange=()=>{fa.bays[+e.dataset.t].type=e.value;renderAll()});box.querySelectorAll('[data-f]').forEach(e=>e.onchange=()=>{fa.bays[+e.dataset.f].frame=e.value;renderAll()});box.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{if(fa.bays.length>1)fa.bays.splice(+e.dataset.r,1);renderAll()})}
function draw2D(){const c=$('plan'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(!state.facades.length)return;const totals=state.facades.map(fa=>fa.bays.reduce((s,b)=>s+b.length,0)),max=Math.max(...totals),scale=Math.min(700/max,420/Math.max(totals[1],totals[3]));const ox=250,oy=145,w=totals[0]*scale,d=totals[1]*scale;x.fillStyle='#e2e8f0';x.fillRect(ox,oy,w,d);x.strokeStyle='#172033';x.lineWidth=5;x.strokeRect(ox,oy,w,d);const sides=[[ox,oy,1,0],[ox+w,oy,0,1],[ox+w,oy+d,-1,0],[ox,oy+d,0,-1]];state.facades.forEach((fa,k)=>{let pos=0;fa.bays.forEach((b,i)=>{const s=sides[k],px=s[0]+s[2]*pos*scale,py=s[1]+s[3]*pos*scale,len=b.length*scale;x.strokeStyle=b.type==='access'?'#dc2626':'#f59e0b';x.lineWidth=10;x.beginPath();x.moveTo(px,py);x.lineTo(px+s[2]*len,py+s[3]*len);x.stroke();x.fillStyle='#172033';x.font='18px sans-serif';x.fillText(b.type==='access'?'A':'',px+s[2]*len/2+8,py+s[3]*len/2-8);pos+=b.length})});x.fillStyle='#172033';x.font='bold 24px sans-serif';x.fillText('Plan des 4 façades',30,45)}
function project(p){const a=state.angle,ca=Math.cos(a),sa=Math.sin(a);return [600+(p[0]-p[1])*ca*28,520+(p[0]+p[1])*sa*13-p[2]*32]}
function line(ctx,a,b,color='#334155',w=3){ctx.strokeStyle=color;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(...project(a));ctx.lineTo(...project(b));ctx.stroke()}
function draw3D(){const c=$('three'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!state.facades.length)return;const L=state.facades[0].bays.reduce((s,b)=>s+b.length,0),D=state.facades[1].bays.reduce((s,b)=>s+b.length,0),H=scaffoldTop();ctx.fillStyle='#e2e8f0';let q=[[0,0,0],[L,0,0],[L,D,0],[0,D,0]].map(project);ctx.beginPath();ctx.moveTo(...q[0]);q.slice(1).forEach(v=>ctx.lineTo(...v));ctx.closePath();ctx.fill();for(let z=state.startHeight;z<=H+.01;z+=state.levelHeight){line(ctx,[0,0,z],[L,0,z]);line(ctx,[L,0,z],[L,D,z]);line(ctx,[L,D,z],[0,D,z]);line(ctx,[0,D,z],[0,0,z])}state.facades.forEach((fa,k)=>{let p=0;fa.bays.forEach(b=>{const coords=k===0?[p,0]:k===1?[L,p]:k===2?[L-p,D]:[0,D-p];for(let z=0;z<=H;z+=state.levelHeight)line(ctx,[coords[0],coords[1],z],[coords[0],coords[1],Math.min(z+state.levelHeight,H)],b.frame==='full'?'#334155':'#7c3aed',4);if(b.type==='access'){const end=p+b.length;const c1=k===0?[p,0]:k===1?[L,p]:k===2?[L-p,D]:[0,D-p],c2=k===0?[end,0]:k===1?[L,end]:k===2?[L-end,D]:[0,D-end];line(ctx,[c1[0],c1[1],state.startHeight],[c2[0],c2[1],H],'#dc2626',7)}p+=b.length})});ctx.fillStyle='#172033';ctx.font='bold 24px sans-serif';ctx.fillText('4 façades — accès en rouge',30,45)}
function materials(){const rows=[],lev=levels();let bays=0,access=0,halfTop=0,halfBottom=0;const byLen={};state.facades.forEach(fa=>fa.bays.forEach(b=>{bays++;byLen[b.length]=(byLen[b.length]||0)+1;if(b.type==='access')access++;if(b.frame==='half-top')halfTop++;if(b.frame==='half-bottom')halfBottom++}));rows.push(['Structure','Socles à vis',bays*2,'Deux files de montants']);rows.push(['Structure','Cadres complets',Math.max(0,(bays+4)*lev-halfTop-halfBottom),'Calcul de base']);if(halfTop)rows.push(['Structure','Demi-cadres supérieurs',halfTop,'Choix manuel']);if(halfBottom)rows.push(['Structure','Demi-cadres inférieurs',halfBottom,'Choix manuel']);Object.entries(byLen).forEach(([l,n])=>{rows.push(['Planchers',`Planchers alu/bois ${f(l)} m`,n*lev,`${n} travées × ${lev} niveaux`]);rows.push(['Protection',`Garde-corps ${f(l)} m`,n*lev,'Façades extérieures'])});rows.push(['Contreventement','Diagonales',Math.ceil(bays/3)*lev,'1 toutes les 3 travées']);rows.push(['Angles','Liaisons d’angle à 90°',4*lev,'Quatre angles']);if(access){rows.push(['Accès','Planchers à trappe',access*lev,'Visible en 2D et 3D']);rows.push(['Accès','Échelles d’accès',access*lev,'Une par niveau et travée d’accès']);rows.push(['Accès','Garde-corps de protection d’accès',access*lev,'À contrôler selon montage'])}return rows}
function renderMaterials(){$('matTitle').textContent=`${state.name} — hauteur ${f(scaffoldTop())} m`;const box=$('matList');box.innerHTML='';let g='';materials().forEach(r=>{if(r[0]!==g){g=r[0];box.insertAdjacentHTML('beforeend',`<h3 class="group">${g}</h3>`)}box.insertAdjacentHTML('beforeend',`<div class="row"><div><strong>${r[1]}</strong><small>${r[3]}</small></div><span class="qty">${r[2]}</span></div>`)})}
function renderSaved(){const a=JSON.parse(localStorage.getItem('scaffr200-v2-projects')||'[]'),b=$('savedList');b.innerHTML=a.length?'':'<p>Aucun chantier.</p>';a.forEach((p,i)=>b.insertAdjacentHTML('beforeend',`<div class="saved"><div><strong>${p.name}</strong><small>${p.facades.length} façades</small></div><button data-open="${i}">Ouvrir</button></div>`));b.querySelectorAll('[data-open]').forEach(e=>e.onclick=()=>{state=a[+e.dataset.open];loadForm();renderAll();switchTab('project')})}
$('save').onclick=()=>{const a=JSON.parse(localStorage.getItem('scaffr200-v2-projects')||'[]');a.unshift(JSON.parse(JSON.stringify(state)));localStorage.setItem('scaffr200-v2-projects',JSON.stringify(a.slice(0,30)));renderSaved()};$('print').onclick=()=>window.print();$('left').onclick=()=>{state.angle-=.18;draw3D()};$('right').onclick=()=>{state.angle+=.18;draw3D()};$('reset').onclick=()=>{state.angle=-.65;draw3D()};let drag=false,last=0;$('three').onpointerdown=e=>{drag=true;last=e.clientX};$('three').onpointermove=e=>{if(drag){state.angle+=(e.clientX-last)/250;last=e.clientX;draw3D()}};window.onpointerup=()=>drag=false;
function loadForm(){$('name').value=state.name;$('mode').value=state.mode;$('startHeight').value=state.startHeight;$('targetHeight').value=state.targetHeight;$('levelHeight').value=state.levelHeight;if(state.facades.length){$('width').value=state.facades[0].target;$('depth').value=state.facades[1].target}}
function renderAll(editor=true){updateStats();if(editor)renderEditor();draw2D();draw3D();renderMaterials();renderSaved()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');makeFacades();
